// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moviesrating.proto

package ru.hixon.movies;

public final class Moviesrating {
  private Moviesrating() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetRatingRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetRatingRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code GetRatingRequest}
   */
  public  static final class GetRatingRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetRatingRequest)
      GetRatingRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetRatingRequest.newBuilder() to construct.
    private GetRatingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetRatingRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetRatingRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.hixon.movies.Moviesrating.internal_static_GetRatingRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.hixon.movies.Moviesrating.internal_static_GetRatingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.hixon.movies.Moviesrating.GetRatingRequest.class, ru.hixon.movies.Moviesrating.GetRatingRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.hixon.movies.Moviesrating.GetRatingRequest)) {
        return super.equals(obj);
      }
      ru.hixon.movies.Moviesrating.GetRatingRequest other = (ru.hixon.movies.Moviesrating.GetRatingRequest) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.hixon.movies.Moviesrating.GetRatingRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.hixon.movies.Moviesrating.GetRatingRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetRatingRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetRatingRequest)
        ru.hixon.movies.Moviesrating.GetRatingRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.hixon.movies.Moviesrating.internal_static_GetRatingRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.hixon.movies.Moviesrating.internal_static_GetRatingRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.hixon.movies.Moviesrating.GetRatingRequest.class, ru.hixon.movies.Moviesrating.GetRatingRequest.Builder.class);
      }

      // Construct using ru.hixon.movies.Moviesrating.GetRatingRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.hixon.movies.Moviesrating.internal_static_GetRatingRequest_descriptor;
      }

      public ru.hixon.movies.Moviesrating.GetRatingRequest getDefaultInstanceForType() {
        return ru.hixon.movies.Moviesrating.GetRatingRequest.getDefaultInstance();
      }

      public ru.hixon.movies.Moviesrating.GetRatingRequest build() {
        ru.hixon.movies.Moviesrating.GetRatingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.hixon.movies.Moviesrating.GetRatingRequest buildPartial() {
        ru.hixon.movies.Moviesrating.GetRatingRequest result = new ru.hixon.movies.Moviesrating.GetRatingRequest(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.hixon.movies.Moviesrating.GetRatingRequest) {
          return mergeFrom((ru.hixon.movies.Moviesrating.GetRatingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.hixon.movies.Moviesrating.GetRatingRequest other) {
        if (other == ru.hixon.movies.Moviesrating.GetRatingRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.hixon.movies.Moviesrating.GetRatingRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.hixon.movies.Moviesrating.GetRatingRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetRatingRequest)
    }

    // @@protoc_insertion_point(class_scope:GetRatingRequest)
    private static final ru.hixon.movies.Moviesrating.GetRatingRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.hixon.movies.Moviesrating.GetRatingRequest();
    }

    public static ru.hixon.movies.Moviesrating.GetRatingRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetRatingRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetRatingRequest>() {
      public GetRatingRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetRatingRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetRatingRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetRatingRequest> getParserForType() {
      return PARSER;
    }

    public ru.hixon.movies.Moviesrating.GetRatingRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetRatingResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetRatingResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string movie = 1;</code>
     */
    java.util.List<java.lang.String>
        getMovieList();
    /**
     * <code>repeated string movie = 1;</code>
     */
    int getMovieCount();
    /**
     * <code>repeated string movie = 1;</code>
     */
    java.lang.String getMovie(int index);
    /**
     * <code>repeated string movie = 1;</code>
     */
    com.google.protobuf.ByteString
        getMovieBytes(int index);
  }
  /**
   * Protobuf type {@code GetRatingResponse}
   */
  public  static final class GetRatingResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetRatingResponse)
      GetRatingResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetRatingResponse.newBuilder() to construct.
    private GetRatingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetRatingResponse() {
      movie_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetRatingResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                movie_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              movie_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          movie_ = movie_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.hixon.movies.Moviesrating.internal_static_GetRatingResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.hixon.movies.Moviesrating.internal_static_GetRatingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.hixon.movies.Moviesrating.GetRatingResponse.class, ru.hixon.movies.Moviesrating.GetRatingResponse.Builder.class);
    }

    public static final int MOVIE_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList movie_;
    /**
     * <code>repeated string movie = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMovieList() {
      return movie_;
    }
    /**
     * <code>repeated string movie = 1;</code>
     */
    public int getMovieCount() {
      return movie_.size();
    }
    /**
     * <code>repeated string movie = 1;</code>
     */
    public java.lang.String getMovie(int index) {
      return movie_.get(index);
    }
    /**
     * <code>repeated string movie = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMovieBytes(int index) {
      return movie_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < movie_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, movie_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < movie_.size(); i++) {
          dataSize += computeStringSizeNoTag(movie_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMovieList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.hixon.movies.Moviesrating.GetRatingResponse)) {
        return super.equals(obj);
      }
      ru.hixon.movies.Moviesrating.GetRatingResponse other = (ru.hixon.movies.Moviesrating.GetRatingResponse) obj;

      boolean result = true;
      result = result && getMovieList()
          .equals(other.getMovieList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMovieCount() > 0) {
        hash = (37 * hash) + MOVIE_FIELD_NUMBER;
        hash = (53 * hash) + getMovieList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.hixon.movies.Moviesrating.GetRatingResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.hixon.movies.Moviesrating.GetRatingResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.hixon.movies.Moviesrating.GetRatingResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetRatingResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetRatingResponse)
        ru.hixon.movies.Moviesrating.GetRatingResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.hixon.movies.Moviesrating.internal_static_GetRatingResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.hixon.movies.Moviesrating.internal_static_GetRatingResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.hixon.movies.Moviesrating.GetRatingResponse.class, ru.hixon.movies.Moviesrating.GetRatingResponse.Builder.class);
      }

      // Construct using ru.hixon.movies.Moviesrating.GetRatingResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        movie_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.hixon.movies.Moviesrating.internal_static_GetRatingResponse_descriptor;
      }

      public ru.hixon.movies.Moviesrating.GetRatingResponse getDefaultInstanceForType() {
        return ru.hixon.movies.Moviesrating.GetRatingResponse.getDefaultInstance();
      }

      public ru.hixon.movies.Moviesrating.GetRatingResponse build() {
        ru.hixon.movies.Moviesrating.GetRatingResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.hixon.movies.Moviesrating.GetRatingResponse buildPartial() {
        ru.hixon.movies.Moviesrating.GetRatingResponse result = new ru.hixon.movies.Moviesrating.GetRatingResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          movie_ = movie_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.movie_ = movie_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.hixon.movies.Moviesrating.GetRatingResponse) {
          return mergeFrom((ru.hixon.movies.Moviesrating.GetRatingResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.hixon.movies.Moviesrating.GetRatingResponse other) {
        if (other == ru.hixon.movies.Moviesrating.GetRatingResponse.getDefaultInstance()) return this;
        if (!other.movie_.isEmpty()) {
          if (movie_.isEmpty()) {
            movie_ = other.movie_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMovieIsMutable();
            movie_.addAll(other.movie_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.hixon.movies.Moviesrating.GetRatingResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.hixon.movies.Moviesrating.GetRatingResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList movie_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMovieIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          movie_ = new com.google.protobuf.LazyStringArrayList(movie_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string movie = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getMovieList() {
        return movie_.getUnmodifiableView();
      }
      /**
       * <code>repeated string movie = 1;</code>
       */
      public int getMovieCount() {
        return movie_.size();
      }
      /**
       * <code>repeated string movie = 1;</code>
       */
      public java.lang.String getMovie(int index) {
        return movie_.get(index);
      }
      /**
       * <code>repeated string movie = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMovieBytes(int index) {
        return movie_.getByteString(index);
      }
      /**
       * <code>repeated string movie = 1;</code>
       */
      public Builder setMovie(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMovieIsMutable();
        movie_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string movie = 1;</code>
       */
      public Builder addMovie(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMovieIsMutable();
        movie_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string movie = 1;</code>
       */
      public Builder addAllMovie(
          java.lang.Iterable<java.lang.String> values) {
        ensureMovieIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, movie_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string movie = 1;</code>
       */
      public Builder clearMovie() {
        movie_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string movie = 1;</code>
       */
      public Builder addMovieBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureMovieIsMutable();
        movie_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetRatingResponse)
    }

    // @@protoc_insertion_point(class_scope:GetRatingResponse)
    private static final ru.hixon.movies.Moviesrating.GetRatingResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.hixon.movies.Moviesrating.GetRatingResponse();
    }

    public static ru.hixon.movies.Moviesrating.GetRatingResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetRatingResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetRatingResponse>() {
      public GetRatingResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetRatingResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetRatingResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetRatingResponse> getParserForType() {
      return PARSER;
    }

    public ru.hixon.movies.Moviesrating.GetRatingResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetRatingRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetRatingRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetRatingResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetRatingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022moviesrating.proto\"\022\n\020GetRatingRequest" +
      "\"\"\n\021GetRatingResponse\022\r\n\005movie\030\001 \003(\t2D\n\014" +
      "MoviesRating\0224\n\tGetRating\022\021.GetRatingReq" +
      "uest\032\022.GetRatingResponse\"\000B\021\n\017ru.hixon.m" +
      "oviesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GetRatingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetRatingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetRatingRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetRatingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetRatingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetRatingResponse_descriptor,
        new java.lang.String[] { "Movie", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
